language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8

env:
  - scala_projects="elasticsearch_scala_coreJS/test"
  - scala_projects="elasticsearch_scala_coreJVM/test elasticsearch_scala_java_client/test"

script:
  - sbt ++$TRAVIS_SCALA_VERSION $scala_projects
