language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8

env:
  - scala_projects="elasticsearch_scala_coreJS/test"
    after="echo NO_COVERAGE"
  - scala_projects="clean coverage elasticsearch_scala_coreJVM/test elasticsearch_scala_java_client/test"
    after="sbt coverageReport coverageAggregate coveralls"

script:
  - sbt -DtestOpt=full ++$TRAVIS_SCALA_VERSION $scala_projects

after_success: $after
