language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8

env:
  global:
    - scala_js="elasticsearch_scala_coreJS/test"
    - scala_jvm="elasticsearch_scala_coreJVM/test elasticsearch_scala_java_clientJVM/test"

script:
  - sbt ++$TRAVIS_SCALA_VERSION $scala_js
  - sbt ++$TRAVIS_SCALA_VERSION $scala_jvm
