package org.elastic.elasticsearch.scala.driver.common

import org.elastic.rest.scala.driver.RestBaseImplicits.CustomTypedToString
import org.elastic.rest.scala.driver.utils.NoJsonHelpers.SimpleObjectDescription
import org.elastic.rest.scala.driver.utils.NoJsonHelpers.{SimpleObjectDescription => obj}

/** Data model types used by the index management resources
  */
trait DataModelIndices {

  /** The base trait for updating aliases of indices */
  trait AliasControlBase extends CustomTypedToString

  /** The base trait for updating aliases of a single index */
  trait AliasControlActionBase extends CustomTypedToString

  /** Add an alias to one or more indexes
    * [[https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html#indices-aliases Docs]]
    * @param alias The alias to add to the index or indices
    * @param index (Only one of `index` or `indices` can be specified)
    *              The index or glob or `_all` to which to add the alias
    * @param indices (Only one of `index` or `indices` can be specified)
    *                A list of indices to which to add the alias
    * @param filter Aliases with filters provide an easy way to create different "views" of the same index.
    *               The filter can be defined using Query DSL and is applied to all Search, Count, Delete By Query and
    *               More Like This operations with this alias
    *               Note that any fields used in filtering must already exist in the mapping
    * @param routing It is possible to associate routing values with aliases. This feature can be used together with
    *                filtering aliases in order to avoid unnecessary shard operations
    * @param search_routing It is possible to associate routing values with aliases.
    *                       This feature can be used together with filtering aliases in order to avoid unnecessary
    *                       shard operations - this param is used to apply routing only to search requests
    * @param index_routing It is possible to associate routing values with aliases.
    *                       This feature can be used together with filtering aliases in order to avoid unnecessary
    *                       shard operations - this param is used to apply routing only to index requests
    */
  case class AddAliasControl
    (alias: String, index: Option[String] = None, indices: Seq[String] = Seq.empty,
     filter: Option[DataModelSearch.qb.QueryElement] = None,
     routing: Option[String] = None, search_routing: Option[String] = None, index_routing: Option[String] = None)
    extends AliasControlActionBase
  {
    @SimpleObjectDescription("obj",
      obj.SimpleObject("add")(
        obj.Field("index"),
        obj.MultiTypeField("indices"),
        obj.Field("alias"),
        obj.Field("filter"),
        obj.Field("routing"),
        obj.Field("search_routing"),
        obj.Field("index_routing")
      )
    )
    override def fromTyped: String = obj.AutoGenerated

  }
  /** Remove an alias from one or more indexes
    * [[https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html#indices-aliases Docs]]
    * Note that a "set" can be accomplished via a remove with `index = Some("*")` and then an add with `indices` set
    * to the required list.
    * @param alias The alias to remove from the index or indices
    * @param index (Only one of `index` or `indices` can be specified)
    *              The index or glob or `_all` from which to remove the alias
    * @param indices (Only one of `index` or `indices` can be specified)
    *                A list of indices from which to remove the alias
    */
  case class RemoveAliasControl
    (alias: String, index: Option[String] = None, indices: Seq[String] = Seq.empty)
    extends AliasControlActionBase
  {
    @SimpleObjectDescription("obj",
      obj.SimpleObject("remove")(
        obj.Field("index"),
        obj.MultiTypeField("indices"),
        obj.Field("alias")
      )
    )
    override def fromTyped: String = obj.AutoGenerated
  }
  /** Remove the specified indexes
    * [[https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html#indices-aliases Docs]]
    * @param index (Only one of `index` or `indices` can be specified)
    *              The index or glob or `_all` to remove
    * @param indices (Only one of `index` or `indices` can be specified)
    *                The list of indexes to remove
    */
  case class RemoveIndexControl
    (index: Option[String] = None, indices: Seq[String] = Seq.empty)
    extends AliasControlActionBase
  {
    @SimpleObjectDescription("obj",
      obj.SimpleObject("remove_index")(
        obj.Field("index"),
        obj.MultiTypeField("indices")
      )
    )
    override def fromTyped: String = obj.AutoGenerated
  }

  /** The control structure for aliases
    * [[https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html#indices-aliases Docs]]
    * @param actions The list of commands to apply to the system
    */
  case class AliasControl(actions: Seq[AliasControlActionBase]) extends AliasControlBase {
    @SimpleObjectDescription("obj",
      obj.Field("actions")
    )
    override def fromTyped: String = obj.AutoGenerated
  }

}
object DataModelIndices extends DataModelIndices
